name: Periodic Health Check

on:
  push: 
    branches:
      - master
  schedule:
    - cron: '00 00 * * THU'

jobs: 
  health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: health
        uses: jtalk/url-health-check-action@v2
        with:
          # Check the following URLs one by one sequentially
          url: https://shrouded-peak-78795.herokuapp.com/health"
